### ISSUE TITLE
PDF 下载等链接失效

### ISSUE THREAD

**Issue by autodataming** [wizardforcel/lcthw-zh#1]
PDF 下载等链接失效

**Comment by wizardforcel** [comment]
等整个翻译完我会同步到gitbook，那时候才会生效。

**Comment by Dali-Deu** [comment]
您好作者，请问如下链接不可用吗？为什么会跳到gitbook首页？需要怎么下载？打赏？升级我自己的gitbook？
https://www.gitbook.com/download/pdf/book/wizardforcel/kali-linux-cookbook
