### ISSUE TITLE
一处错误

### ISSUE THREAD

**Issue by cute** [wizardforcel/lcthw-zh#10]
`C语言编程的核心能力之一就是链接OS所提供的库。链接是一种为你的程序天机额外特性的方法，这些特性有其它人在系统中创建并打包。你已经使用了一些自动包含的标准库，但是我打算对**哭**的不同类型和它们的作用做个解释。`

**哭**应为**库**

https://github.com/wizardforcel/lcthw-zh/edit/master/ex29.md

**Comment by wizardforcel** [comment]
fixed.
