### ISSUE TITLE
Google Translater?

### ISSUE THREAD

**Issue by darkr4y** [wizardforcel/lcthw-zh#5]
如 
## 核心能力

这一章节 

> 我假设你来自于一种弱者的语言 

很显然,Python和Ruby你可以称之为弱类型语言，但是这样的机翻，加上自己组织使语言通顺的翻译，质量真的很低。

**Comment by darkr4y** [comment]
文章中还有大量诸如此类的翻译，我觉得做技术类翻译首先应该是熟悉和使用过这些语言，一些术语都有很多约定俗成的叫法，如果怕产生歧义，可以在术语旁使用类似

> 结构体(Struct) 

这样的方式来突出，且也有利于读者自行查询一些相关的关键字，与原版进行对比等。

**Comment by wizardforcel** [comment]
作者此处的意图明显是“弱者所用的语言”，来标榜C是“真正的程序员”所使用的语言，并没有提到什么弱类型语言，是你没理解出作者的意思。

**Comment by wizardforcel** [comment]
另外我没有使用CAT，是自己照着原文手打上去的。文章的确没有润色，而且作者的措辞**本来就不是很好**。作者简直是**滥用**转折逻辑，各种代词（this、it）不明所以，并且废话很多（比如前面说“by doing ...”，后面又说"to do it"）。

觉得烂你可以不看，或者提PR。

以上。

**Comment by darkr4y** [comment]
OK，我会继续Review，合适的时候提出PR。
**Thx4 reply**

**Comment by darkr4y** [comment]
Btw 同时还是感谢提供了翻译，做了知识共享。恕我冒昧的提出了以上些许建议。

**Comment by wizardforcel** [comment]
由于我的键盘不太灵，有些地方会遗漏一些虚词（比如“的”），以及还有一些比较拗口的句子，你如果能找出来，就发上来吧。
